runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: markupsafe
  version: "0.23"
- name: ssl
  version: "2.7.11"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*$
- ^Pipfile$
- ^Pipfile.lock$
- ^lib/markupsafe/.*$
- ^lib/MarkupSafe-.*$
